# CMake generated Testfile for 
# Source directory: /home/ubuntu/sil-kit/SilKit/source/core/vasio
# Build directory: /home/ubuntu/sil-kit/build/SilKit/source/core/vasio
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Test_VAsioConnection "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_VAsioConnection_gtestresults.xml" "--gtest_filter=Test_VAsioConnection.*")
set_tests_properties(Test_VAsioConnection PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;153;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_VAsioSerdes "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_VAsioSerdes_gtestresults.xml" "--gtest_filter=Test_VAsioSerdes.*")
set_tests_properties(Test_VAsioSerdes PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;155;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_SerializedMessage "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_SerializedMessage_gtestresults.xml" "--gtest_filter=Test_SerializedMessage.*")
set_tests_properties(Test_SerializedMessage PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;156;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_Uri "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_Uri_gtestresults.xml" "--gtest_filter=Test_Uri.*")
set_tests_properties(Test_Uri PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;157;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_TransformAcceptorUris "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_TransformAcceptorUris_gtestresults.xml" "--gtest_filter=Test_TransformAcceptorUris.*")
set_tests_properties(Test_TransformAcceptorUris PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;158;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_VAsioCapabilities "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_VAsioCapabilities_gtestresults.xml" "--gtest_filter=Test_VAsioCapabilities.*")
set_tests_properties(Test_VAsioCapabilities PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;159;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_IoContext "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_IoContext_gtestresults.xml" "--gtest_filter=Test_IoContext.*")
set_tests_properties(Test_IoContext PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;161;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_AsioIoContext "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_AsioIoContext_gtestresults.xml" "--gtest_filter=Test_AsioIoContext.*")
set_tests_properties(Test_AsioIoContext PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;162;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_TracingMacrosDetails "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_TracingMacrosDetails_gtestresults.xml" "--gtest_filter=Test_TracingMacrosDetails.*")
set_tests_properties(Test_TracingMacrosDetails PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;163;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_ConnectPeer "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_ConnectPeer_gtestresults.xml" "--gtest_filter=Test_ConnectPeer.*")
set_tests_properties(Test_ConnectPeer PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;165;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_ConnectKnownParticipants "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_ConnectKnownParticipants_gtestresults.xml" "--gtest_filter=Test_ConnectKnownParticipants.*")
set_tests_properties(Test_ConnectKnownParticipants PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;166;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
add_test(Test_ParticipantVersion "/home/ubuntu/sil-kit/build/Release/SilKitUnitTests" "--gtest_output=xml:Test_ParticipantVersion_gtestresults.xml" "--gtest_filter=Test_ParticipantVersion.*")
set_tests_properties(Test_ParticipantVersion PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/build/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;171;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/core/vasio/CMakeLists.txt;0;")
