# CMake generated Testfile for 
# Source directory: /home/ubuntu/sil-kit/SilKit/source/capi
# Build directory: /home/ubuntu/sil-kit/qnxBuild/SilKit/source/capi
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Test_CapiInterfaces "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiInterfaces_gtestresults.xml" "--gtest_filter=Test_CapiInterfaces.*")
set_tests_properties(Test_CapiInterfaces PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;53;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiCan "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiCan_gtestresults.xml" "--gtest_filter=Test_CapiCan.*")
set_tests_properties(Test_CapiCan PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;54;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiEthernet "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiEthernet_gtestresults.xml" "--gtest_filter=Test_CapiEthernet.*")
set_tests_properties(Test_CapiEthernet PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;55;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiFlexray "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiFlexray_gtestresults.xml" "--gtest_filter=Test_CapiFlexray.*")
set_tests_properties(Test_CapiFlexray PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;56;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiData "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiData_gtestresults.xml" "--gtest_filter=Test_CapiData.*")
set_tests_properties(Test_CapiData PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;57;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiRpc "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiRpc_gtestresults.xml" "--gtest_filter=Test_CapiRpc.*")
set_tests_properties(Test_CapiRpc PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;58;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiLogger "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiLogger_gtestresults.xml" "--gtest_filter=Test_CapiLogger.*")
set_tests_properties(Test_CapiLogger PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;59;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiVersion "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiVersion_gtestresults.xml" "--gtest_filter=Test_CapiVersion.*")
set_tests_properties(Test_CapiVersion PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;60;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiSilKit "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiSilKit_gtestresults.xml" "--gtest_filter=Test_CapiSilKit.*")
set_tests_properties(Test_CapiSilKit PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;62;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiParticipantStateHandling "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiParticipantStateHandling_gtestresults.xml" "--gtest_filter=Test_CapiParticipantStateHandling.*")
set_tests_properties(Test_CapiParticipantStateHandling PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;63;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiTimeSync "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiTimeSync_gtestresults.xml" "--gtest_filter=Test_CapiTimeSync.*")
set_tests_properties(Test_CapiTimeSync PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;64;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiLin "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiLin_gtestresults.xml" "--gtest_filter=Test_CapiLin.*")
set_tests_properties(Test_CapiLin PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;65;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
add_test(Test_CapiSymbols "/home/ubuntu/sil-kit/qnxBuild/Release/SilKitUnitTests" "--gtest_output=xml:Test_CapiSymbols_gtestresults.xml" "--gtest_filter=Test_CapiSymbols.*")
set_tests_properties(Test_CapiSymbols PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/qnxBuild/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;66;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/capi/CMakeLists.txt;0;")
