# CMake generated Testfile for 
# Source directory: /home/ubuntu/sil-kit/SilKit/source/dashboard
# Build directory: /home/ubuntu/sil-kit/SilKit/source/dashboard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Test_DashboardCachingSilKitEventHandler "/home/ubuntu/sil-kit/Release/SilKitDashboardTests" "--gtest_output=xml:Test_DashboardCachingSilKitEventHandler_gtestresults.xml" "--gtest_filter=Test_DashboardCachingSilKitEventHandler.*")
set_tests_properties(Test_DashboardCachingSilKitEventHandler PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;140;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;0;")
add_test(Test_DashboardSilKitEventQueue "/home/ubuntu/sil-kit/Release/SilKitDashboardTests" "--gtest_output=xml:Test_DashboardSilKitEventQueue_gtestresults.xml" "--gtest_filter=Test_DashboardSilKitEventQueue.*")
set_tests_properties(Test_DashboardSilKitEventQueue PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;149;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;0;")
add_test(Test_DashboardSilKitEventHandler "/home/ubuntu/sil-kit/Release/SilKitDashboardTests" "--gtest_output=xml:Test_DashboardSilKitEventHandler_gtestresults.xml" "--gtest_filter=Test_DashboardSilKitEventHandler.*")
set_tests_properties(Test_DashboardSilKitEventHandler PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;157;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;0;")
add_test(Test_DashboardSilKitToOatppMapper "/home/ubuntu/sil-kit/Release/SilKitDashboardTests" "--gtest_output=xml:Test_DashboardSilKitToOatppMapper_gtestresults.xml" "--gtest_filter=Test_DashboardSilKitToOatppMapper.*")
set_tests_properties(Test_DashboardSilKitToOatppMapper PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;167;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;0;")
add_test(Test_DashboardSystemServiceClient "/home/ubuntu/sil-kit/Release/SilKitDashboardTests" "--gtest_output=xml:Test_DashboardSystemServiceClient_gtestresults.xml" "--gtest_filter=Test_DashboardSystemServiceClient.*")
set_tests_properties(Test_DashboardSystemServiceClient PROPERTIES  WORKING_DIRECTORY "/home/ubuntu/sil-kit/Release" _BACKTRACE_TRIPLES "/home/ubuntu/sil-kit/SilKit/cmake/SilKitTest.cmake;125;add_test;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;176;add_silkit_test_to_executable;/home/ubuntu/sil-kit/SilKit/source/dashboard/CMakeLists.txt;0;")
